C ******* COMMON BLOCK FOR  HYBRID SIMULATION CODE *******

C.........ADIABATIC ELECTRON FLUID

C  BY CHANGING THE FOLLOWING PARAMETERS, YOU CAN CHOOSE SIMULATION
C  PARAMETERS.

      PARAMETER (ITEST=000)
      PARAMETER (DXX=0.5, DYY=0.5, DTT=0.025)
C     PARAMETER (III=560, JJJ=  64, IBND=3)
C     PARAMETER (III=120, JJJ=  64, IBND=2)
      PARAMETER (III=400, JJJ=64, IBND=3)
      PARAMETER (JSIZE=JJJ/2)
      PARAMETER (THBN=70.,PHIB= 0.)
C      PARAMETER (THBN=70.,PHIB= 0.)
C.....BX0=COS(THBN), BY0 = SIN(THBN)*COS(PHIB), BZ0=SIN(THBN)*SIN(PHIB)

      PARAMETER (RVA=5.5, VSEP=175., RNTHRE=2.0, DELTA=6., DUPSTR=15.)
      PARAMETER (VFS=1.5)
C     PARAMETER (ITMAXX=500,IDTCHK=100 )
      PARAMETER (ITMAXX=800,IDTCHK=100 )
CC    PARAMETER (IDTT= 2500, IDTP= 2500, IDTREF=2500,IDTSHP=2500)
C     PARAMETER (IDTT= 100, IDTP= 100, IDTREF=100, IDTSHP=100)
      PARAMETER (IDTT= 100, IDTP= 100, IDTREF=1000, IDTSHP=500)
C     PARAMETER (IDPHAS=100)
      PARAMETER (IDPHAS=3900)
C
C........Parameter set for species
C     No. of species
      PARAMETER (NSPP=2)
C     Dimmension set
      DIMENSION MASS(NSPP), NCHG(NSPP), DENSIT(NSPP), BETA_SPC(NSPP)
      DIMENSION DIF_IS(NSPP)
C     set values for each spieces
C
C     MASS = particle mass
C     NCHG = particle charge
C     DENSIT= density of particle in ratio to Proton
C     BETA_SPC= plasma beta for each particle
C     DIF_IS = difference to DUPSTR
C         DUPSTR is roughly equal to gyro-radi for H
C

      DATA MASS/1,1/
      DATA NCHG/1,1/
      DATA DENSIT/1.0000, 1.0000/
C      DATA DENSIT/1.0000, 0.100/
      DATA BETA_SPC/0.055, 0.055/
C
      DATA DIF_IS/0.0, 15./
C
C.......Set values for electron
CC    PARAMETER (EBETAA=0.0, EGAMMM=5./3.)
      PARAMETER (EBETAA=0.4, EGAMMM=5./3.)

      PARAMETER (NCXX1= 8, NCYY1= 8, NHE=1)
      PARAMETER (NCC1=NCXX1*NCYY1, NJJJ=NCC1*JJJ)
      PARAMETER (NNN1=NCC1*(III-1)*JJJ)
C........NNN WOULD BE ABOUT (NNN1+NCC1*JJJ*RVA*TMAX/DX)*1.2
C      PARAMETER (NNN=2500000)
      PARAMETER (NNN=4000000)
CC    PARAMETER (NNN=8000000)
C
C......
      PARAMETER (LLFLD=2)
C
C...... Set eta
CC    PARAMETER (ETA  =1.0E-3)
C     PARAMETER (ETA  =1.0E-7)
C   orignal value by C. KATO
      PARAMETER (ETA  =1.0E-7)
C
C...... Set scattering time scale
C...... If "TSCAT < 0" : skip the subroutine "SCATTER"
C      PARAMETER (TSCAT  =5)
       PARAMETER (TSCAT  =-1)
C     PARAMETER (TSCAT  =20)
C
C...... Set run condition
C...... 0 : First run, 1 : restart, 2:recover from unexpected stop
      PARAMETER (ISTRT_CHK =0)
C saving data for unexpected termination
      PARAMETER (IDT_SAV=1500)

C
C=======FOR SPLIN4
      PARAMETER (MMI=III,MI2=2*MMI)
      PARAMETER (LLI=3*MMI,LI2=3000)
      PARAMETER (MMJ=JJJ,MJ2=2*MMJ)
      PARAMETER (LLJ=3*MMJ,LJ2=1000)

C     DXX, DYY .... GRID SIZES
C     DTT      .... TIME INCREMENT
C     III * JJJ ... SYSTEM SIZE
C     ISP,IIIP,JJJP ... ISP IS FOR PERIODIC SPLINE
C     ITMAXX    ... MAX. TIME STEP
C     IDTT, IDTENN    TIME INTERVALS FOR DIAGNOSIS
C
C     NCXX1*NCYY1.... NUMBER OF PARTICLES PER CELL (SPECIES 1)
C     UTHX1..UTHZ1  THERMAL VELOCITIES IN XYZ DIRECTIONS
C
C     BX00,BY00,BZ00  INITIAL MAGNETIC FIELD VECTOR
C                     (HOMOGENEOUS COMPONENT)
C     EBETAA   .... ELECTRON BETA ?
C     EGAMMM   .... ELECTRON GAMMA ?
C     ETA      .... RESISTIVITY ?
C     LLFLD    .... NUMBER OF FIELD SUBCYCLING
C     TSCAT    .... SCATTERING TIME
C     NSPP     .... No of particle sort
C                   1 = p ; 2 = p + He

C=======================================================================
C    THE FOLLOWING IS THE FIXED PART.
C=======================================================================

      PARAMETER (IIIP2=III+2, JJJP2=JJJ+2)
      PARAMETER (MAXV=64)
      PARAMETER (IVRMX=8)

      CHARACTER*100 VERSN(IVRMX)

C     COMMON/PARA0 /NSP
      COMMON/PARA0 /NSP, ITSAV, ITSTRT
      COMMON/PARA1 /DX,DY,IMAX,JMAX,XMAX,YMAX
      COMMON/PARA2 /DT,DT2,DT22,ITMAX,IDT,IDTENE,IT, TIME, DDT, LFLD
      COMMON/PARA3 /UTHX1(NSPP),UTHY1(NSPP),UTHZ1(NSPP),BETAI(NSPP)
      COMMON/PARA31/GGG1(NSPP),GGG2(NSPP),VTHSEP(NSPP)
      COMMON/PARA32/MSPEC(NSPP),LSPEC(NSPP),DENS(NSPP)
      COMMON/PARA4 /NCX1,NCY1,NC1,NMAX1,NINJ0
      COMMON/PARA6 /NMAX(NSPP)
      COMMON/PARA7 /GDX, GDY, GDX5, GDY5, GDX3, GDY3, NCROSS
      COMMON/PARIN /BX0,BY0,BZ0,EBETA,EGAMM,PTOEN
      COMMON/SPLIT /ICOUNT,DXX1,RVA1,DTT1,HELP
       

      COMMON/PTCL10/XP0   (NNN,NSPP),YP0 (NNN,NSPP)
      COMMON/PTCL11/XP1   (NNN,NSPP),YP1 (NNN,NSPP)
      COMMON/PTCL2 /VXPH  (NNN,NSPP),VYPH(NNN,NSPP),VZPH(NNN,NSPP)
      COMMON/PTCL30/SMM   (NNN,NSPP),SMP (NNN,NSPP)
      COMMON/PTCL31/SPM   (NNN,NSPP),SPP (NNN,NSPP)
C  To check probability of SCATTERING
C     COMMON/PTCL4 /NFLAG (NNN,NSPP),GGG (NNN,NSPP)
      COMMON/PTCL4 /NFLAG (NNN,NSPP),GGG (NNN,NSPP), TAU(NNN,NSPP)

      COMMON/FILD1/ BX  (III,JJJ), BY   (III,JJJ), BZ  (III,JJJ)
      COMMON/FILD2/ BXH (III,JJJ), BYH  (III,JJJ), BZH (III,JJJ)
      COMMON/FILD3/ CX  (III,JJJ), CY   (III,JJJ), CZ  (III,JJJ)
      COMMON/FILD4/ PE  (III,JJJ), DXPE (III,JJJ), DYPE(III,JJJ)
C      COMMON/FILD5/ PEH (III,JJJ), BND(0:III, JJJ)
      COMMON/FILD5/ PEH (III,JJJ), BND(0:IBND+1, JJJ)
      COMMON/FILD6/ VEX (III,JJJ), VEY  (III,JJJ), VEZ (III,JJJ)
      COMMON/FILD7/ EX (III,JJJ), EY   (III,JJJ), EZ  (III,JJJ)
      COMMON/MMMMM/ BTT(III,JJJ)
      COMMON/MMNT1/ RWN   (III,JJJ), RWH   (III,JJJ), RWN1  (III,JJJ)
      COMMON/MMNT2/ VXH   (III,JJJ), VYH   (III,JJJ), VZH   (III,JJJ)
      COMMON/MMNT3/ VXHBF (III,JJJ), VYHBF (III,JJJ), VZHBF (III,JJJ)
      COMMON/MMNT4/ VXHBF2(III,JJJ), VYHBF2(III,JJJ), VZHBF2(III,JJJ)
      COMMON/MMNT5/ VXHBF3(III,JJJ), VYHBF3(III,JJJ), VZHBF3(III,JJJ)
      COMMON/MMNT6/ VXN   (III,JJJ), VYN   (III,JJJ), VZN   (III,JJJ)
      COMMON/MMNT7/ RVXHA (III,JJJ), RVYHA (III,JJJ), RVZHA (III,JJJ)
      COMMON/MMNT8/ RVXHB (III,JJJ), RVYHB (III,JJJ), RVZHB (III,JJJ)
      COMMON/MMNT9/ RTXHB (III,JJJ), RTYHB (III,JJJ), RTZHB (III,JJJ)
      COMMON/MMNT10/TXH   (III,JJJ), TYH   (III,JJJ), TZH   (III,JJJ)

      COMMON/MMNS10/ RWNS   (III,JJJ,NSPP)
      COMMON/MMNS11/ RWHS   (III,JJJ,NSPP)
      COMMON/MMNS12/ RWN1S  (III,JJJ,NSPP)
      COMMON/MMNS20/ VXHS   (III,JJJ,NSPP)
      COMMON/MMNS21/ VYHS   (III,JJJ,NSPP)
      COMMON/MMNS22/ VZHS   (III,JJJ,NSPP)
      COMMON/MMNS60/ VXNS   (III,JJJ,NSPP)
      COMMON/MMNS61/ VYNS   (III,JJJ,NSPP)
      COMMON/MMNS62/ VZNS   (III,JJJ,NSPP)
      COMMON/MMNS70/ RVXHAS (III,JJJ,NSPP)
      COMMON/MMNS71/ RVYHAS (III,JJJ,NSPP)
      COMMON/MMNS72/ RVZHAS (III,JJJ,NSPP)
      COMMON/MMNS80/ RVXHBS (III,JJJ,NSPP)
      COMMON/MMNS81/ RVYHBS (III,JJJ,NSPP)
      COMMON/MMNS82/ RVZHBS (III,JJJ,NSPP)
      COMMON/MMNS90/ RTXP   (III,JJJ,NSPP)
      COMMON/MMNS91/ RTYP   (III,JJJ,NSPP)
      COMMON/MMNS92/ RTZP   (III,JJJ,NSPP)
      COMMON/MMNS01/ TXP    (III,JJJ,NSPP)
      COMMON/MMNS01/ TYP    (III,JJJ,NSPP)
      COMMON/MMNS02/ TZP    (III,JJJ,NSPP)
      COMMON/MMNS03/ RVXP   (III,JJJ,NSPP)
      COMMON/MMNS04/ RVYP   (III,JJJ,NSPP)
      COMMON/MMNS05/ RVZP   (III,JJJ,NSPP)
      COMMON/MMNS06/ RWP    (III,JJJ,NSPP)

C     COMMON/MMNS90/ RTXP   (III,JJJ,NSPP), RTX (III,JJJ)
C     COMMON/MMNS91/ RTYP   (III,JJJ,NSPP), RTY (III,JJJ)
C     COMMON/MMNS92/ RTZP   (III,JJJ,NSPP), RTZ (III,JJJ)
C     COMMON/MMNS01/ TXP    (III,JJJ,NSPP)
C     COMMON/MMNS01/ TYP    (III,JJJ,NSPP)
C     COMMON/MMNS02/ TZP    (III,JJJ,NSPP), TZ  (III,JJJ)
C     COMMON/MMNS03/ RVXP   (III,JJJ,NSPP), RVX (III,JJJ)
C     COMMON/MMNS04/ RVYP   (III,JJJ,NSPP), RVY (III,JJJ)
C     COMMON/MMNS05/ RVZP   (III,JJJ,NSPP), RVZ (III,JJJ)
C     COMMON/MMNS06/ RWP    (III,JJJ,NSPP), RW  (III,JJJ)

C     COMMON/SHCK1/ XSHK(JJJ)
      COMMON/SHCK1/ XSHK(JJJ),ICOUNT_SCT,XSHKOLD(JJJ)

      COMMON/MESH1/II(0:III),IP(III),JJ(0:JJJ),JP(JJJ),JSS(0:JJJ)

***...FOR SPLINE

      COMMON/SPL1 /QQ(MMI,MMJ)

      COMMON/WORK1/WRKT(III,JJJ,MAXV)
      COMMON/WORK2/QX (III,JJJ)     ,QY(III,JJJ)      ,QZ(III,JJJ)
      COMMON/WORK3/QXS(III,JJJ,NSPP),QYS(III,JJJ,NSPP),QZS(III,JJJ,NSPP)

      COMMON/NOTE0/VERSN
C-------- ENF of Parameter setting --------


